include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    constant_identifier_names: false
    # prefer_const_literals_to_create_immutables: false
    # prefer_const_declarations: false
    # prefer_const_constructors: false