name: cuidapet_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  asuka: ^2.0.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  firebase_remote_config: ^1.0.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_mobx: ^2.0.3+2
  flutter_modular: ^4.3.1
  flutter_screenutil: ^5.0.3
  flutter_secure_storage: ^5.0.2
  logger: ^1.1.0
  mobx: ^2.0.6+1
  shared_preferences: ^2.0.12
  validatorless: ^1.2.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - .env
  fonts:
    - family: CuidapetIcons
      fonts:
        - asset: assets/fonts/CuidapetIcons.ttf
