name: cuidapet_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  asuka: ^2.0.0-nullsafety.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.3+2
  flutter_modular: ^3.3.1
  flutter_screenutil: ^5.0.3
  mobx: ^2.0.6+1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2

flutter:
  uses-material-design: true
