name: cuidapet_supplier_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  asuka: ^2.0.0+1
  bloc: ^8.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  equatable: ^2.0.3
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_modular: ^4.5.0
  flutter_screenutil: ^5.3.1
  flutter_typeahead: ^3.2.4
  google_place: ^0.4.7
  logger: ^1.1.0
  steps_indicator: ^1.3.0
  validatorless: ^1.2.1
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
